MvcMovie/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class FilmController : Controller
    {
        private MovieDBContext db = new MovieDBContext();

        // GET: Film
        public ActionResult Index(string filmGenre, string searchString)
        {
            // Get genre list 
            var GenreList = new List<String>();
            var GenreQry = from g in db.Movies
                           orderby g.Genre
                           select g.Genre;

            GenreList.AddRange(GenreQry.Distinct());
            ViewBag.filmGenre = new SelectList(GenreList);

            var film = from m in db.Movies
                       select m;
            if (!string.IsNullOrEmpty(filmGenre))
            {
                film = film.Where(g => g.Genre.Contains(filmGenre));

            }

            if (!string.IsNullOrEmpty(searchString))
            {
                film = film.Where(m => m.Title.Contains(searchString));
            }
            return View(film);
        }
        // GET: Film/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: Film/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID, Title, ReleaseDate, Genre, Price, Rating")] Movie film)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(film);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(film);
        }
        // GET: Film/Edit/1
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                ViewBag.Error = "Id is not avaiable!";
                return View();
            }
            Movie film = db.Movies.Find(id);
            if (film == null)
            {
                ViewBag.Error = "Film is not avaiable!";
                return View();
            }
            return View(film);
        }
        // POST: Film/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Movie film)
        {
            if (ModelState.IsValid)
            {
                db.Entry(film).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.Error = "Edit error";
            return View(film);
        }

        // GET: Film/Detail/1
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                ViewBag.Error = "Id is not avaiavle!";
                return View();
            }
            Movie film = db.Movies.Find(id);
            if (film == null)
            {
                ViewBag.Error = "Film is not avaiavle!";
                return View();
            }
            return View(film);
        }

        // GET: Film/Delete/1
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                ViewBag.Error = "Id is not avaiable!";
                return View();
            }
            Movie film = db.Movies.Find(id);
            if (film == null)
            {
                ViewBag.Error = "Film is not avaiable!";
                return View();
            }
            return View(film);

        }

        // POST: Film/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(FormCollection fcNotUsed, int id = 0)
        {
            Movie film = db.Movies.Find(id);
            if (film == null)
            {
                ViewBag.Error = "Film is not delete!";
                return View();
            }
            db.Movies.Remove(film);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

MvcMovie/Controllers/HelloWorldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMovie.Controllers
{
    public class HelloWorldController : Controller
    {
        //
        //GET : /HelloWorld/
        public ActionResult Index()
        {
            //return "This is my <b>default</b> action..";
            return View();
        }
        //
        //GET: /HelloWorld/Welcome/
        // public string Welcome()
        //{
        //    return "This is the Welcome action method...";
        //}

        ////GET: /HelloWorld/Welcome?name=Scot&numtimes=4
        //public string Welcome(string name, int numTimes = 1)
        //{
        //    return HttpUtility.HtmlEncode("Hello " + name + ", NumTime is: " + numTimes);

        //}

        //GET: /HelloWorld/Welcome?name=Scot&numtimes=4
        //public string Welcome(string name, int id = 1)
        //{
        //    return HttpUtility.HtmlEncode("Hello " + name + ", ID is: " + id);

        //}
        public ActionResult Welcome(string name, int numTimes = 1)
        {
            ViewBag.Message = "Hello " + name;
            ViewBag.NumTimes = numTimes;

            return View();

        }
        public ActionResult Hello()
        {
            return View();
        }
    }
}

MvcMovie/Views/Shared/_FilmLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Movie App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Movie App", "Index", "Film", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Welcome", "Welcome", "HelloWorld")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcMovie/Views/Shared/_HomeBarPartial.cshtml
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Movie App", "Index", "Film", null, new { @class = "navbar-brand" })
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            <li>@Html.ActionLink("Welcome", "Welcome", "HelloWorld")</li>
        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</div>

MvcMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Movie App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @Html.Partial("_HomeBarPartial")
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>